data:
  train_dir: "FER-2013/train_balanced"
  img_size: 48
  batch_size: 64
  validation_split: 0.2
  dataset_mean: 0.5147
  dataset_std: 0.2536

training:
  epochs: 50
  learning_rate: 0.001
  early_stop_patience: 10
  reduce_lr_factor: 0.2
  reduce_lr_patience: 5
  min_lr: 0.00001

model:
  dropout_conv: 0.4
  dropout_dense: 0.5
  dense_units: 256

  