
# @hydra.main(config_path="configs", config_name="config", version_base=None)

# Config selection


defaults:
  dataloader: default
  script: train
  paths: local # local or ailab


  mlflow:
    name: tracker
    tracking_uri: "http://172.24.198.42:5050"

  deepspeed:
    config_path: configs/ds_config.json

# Shared params
seed: 42
