
# @hydra.main(config_path="configs", config_name="config", version_base=None)

# Test
test_script:
  data:
    data_path: "data"
    checkpoint_path: "checkpoint/random_unet.tar"
    output_path: "test_output_images"
    train_split: "train-standard"
    val_split: "val"

  dataloader:
    train_batch_size: 512
    val_batch_size: 1
    train_shuffle: true
    val_shuffle: false
    num_workers: 16


# Train
train_script:
  seed: 42
  data:
    data_path: "FER-2013/train_balanced"
    img_size: 48
    batch_size: 64
    validation_split: 0.2
    dataset_mean: 0.5147
    dataset_std: 0.2536

  training:
    epochs: 50
    learning_rate: 0.001
    early_stop_patience: 10
    reduce_lr_factor: 0.2
    reduce_lr_patience: 5
    min_lr: 0.00001

  model:
    dropout_conv: 0.4
    dropout_dense: 0.5
    dense_units: 256

  dataloader:
    train_batch_size: 512
    val_batch_size: 1
    train_shuffle: true
    val_shuffle: false
    num_workers: 16

  mlflow:
    name: tracker
    tracking_uri: "http://172.24.198.42:5050"

  deepspeed:
    config_path: configs/ds_config.json
